version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./docker/postgres.env
    ports:
      - 5432:5432
    networks:
      - transcendence
    command: postgres -c 'hba_file=/var/lib/postgresql/pg_hba.conf'
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker/pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 5050:80
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    networks:
      - transcendence
    depends_on:
      - postgres
    env_file:
      - ./docker/pgadmin.env

  backend:
    build:
      context: ./docker
      dockerfile: ./backend.dockerfile
    image: backend
    container_name: backend
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - transcendence
    volumes:
      - ./backend:/app
    restart: unless-stopped
    env_file:
      - ./docker/backend.env
    tty: true

  frontend:
    build:
      context: ./docker
      dockerfile: ./frontend.dockerfile
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 8080:8080
    networks:
      - transcendence
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    env_file:
      - ./docker/frontend.env
    tty: true

volumes:
  data:

networks:
  transcendence: